Write-Host "Starting preplot batch job..."

preplot ..\UINLET\UINLET_Animate_0.plt .\UINLET_Animate_0.plt                                                                              
preplot ..\UINLET\UINLET_Animate_1.plt .\UINLET_Animate_1.plt                                                                              
preplot ..\UINLET\UINLET_Animate_2.plt .\UINLET_Animate_2.plt                                                                              
preplot ..\UINLET\UINLET_Animate_3.plt .\UINLET_Animate_3.plt                                                                              
preplot ..\UINLET\UINLET_Animate_4.plt .\UINLET_Animate_4.plt                                                                              
preplot ..\UINLET\UINLET_Animate_5.plt .\UINLET_Animate_5.plt                                                                              
preplot ..\UINLET\UINLET_Animate_6.plt .\UINLET_Animate_6.plt                                                                              
preplot ..\UINLET\UINLET_Animate_7.plt .\UINLET_Animate_7.plt                                                                              
preplot ..\UINLET\UINLET_Animate_8.plt .\UINLET_Animate_8.plt                                                                              
preplot ..\UINLET\UINLET_Animate_9.plt .\UINLET_Animate_9.plt                                                                              
preplot ..\UINLET\UINLET_Animate_10.plt .\UINLET_Animate_10.plt                                                                             
preplot ..\UINLET\UINLET_Animate_11.plt .\UINLET_Animate_11.plt                                                                             
preplot ..\UINLET\UINLET_Animate_12.plt .\UINLET_Animate_12.plt                                                                             
preplot ..\UINLET\UINLET_Animate_13.plt .\UINLET_Animate_13.plt                                                                             
preplot ..\UINLET\UINLET_Animate_14.plt .\UINLET_Animate_14.plt                                                                             
preplot ..\UINLET\UINLET_Animate_15.plt .\UINLET_Animate_15.plt                                                                             
preplot ..\UINLET\UINLET_Animate_16.plt .\UINLET_Animate_16.plt                                                                             
preplot ..\UINLET\UINLET_Animate_17.plt .\UINLET_Animate_17.plt                                                                             
preplot ..\UINLET\UINLET_Animate_18.plt .\UINLET_Animate_18.plt                                                                             
preplot ..\UINLET\UINLET_Animate_19.plt .\UINLET_Animate_19.plt                                                                             
preplot ..\UINLET\UINLET_Animate_20.plt .\UINLET_Animate_20.plt                                                                             
preplot ..\UINLET\UINLET_Animate_21.plt .\UINLET_Animate_21.plt                                                                             
preplot ..\UINLET\UINLET_Animate_22.plt .\UINLET_Animate_22.plt                                                                             
preplot ..\UINLET\UINLET_Animate_23.plt .\UINLET_Animate_23.plt                                                                             
preplot ..\UINLET\UINLET_Animate_24.plt .\UINLET_Animate_24.plt                                                                             
preplot ..\UINLET\UINLET_Animate_25.plt .\UINLET_Animate_25.plt                                                                             
preplot ..\UINLET\UINLET_Animate_26.plt .\UINLET_Animate_26.plt                                                                             
preplot ..\UINLET\UINLET_Animate_27.plt .\UINLET_Animate_27.plt                                                                             
preplot ..\UINLET\UINLET_Animate_28.plt .\UINLET_Animate_28.plt                                                                             
preplot ..\UINLET\UINLET_Animate_29.plt .\UINLET_Animate_29.plt                                                                             
preplot ..\UINLET\UINLET_Animate_30.plt .\UINLET_Animate_30.plt                                                                             
preplot ..\UINLET\UINLET_Animate_31.plt .\UINLET_Animate_31.plt                                                                             
preplot ..\UINLET\UINLET_Animate_32.plt .\UINLET_Animate_32.plt                                                                             
preplot ..\UINLET\UINLET_Animate_33.plt .\UINLET_Animate_33.plt                                                                             
preplot ..\UINLET\UINLET_Animate_34.plt .\UINLET_Animate_34.plt                                                                             
preplot ..\UINLET\UINLET_Animate_35.plt .\UINLET_Animate_35.plt                                                                             
preplot ..\UINLET\UINLET_Animate_36.plt .\UINLET_Animate_36.plt                                                                             
preplot ..\UINLET\UINLET_Animate_37.plt .\UINLET_Animate_37.plt                                                                             
preplot ..\UINLET\UINLET_Animate_38.plt .\UINLET_Animate_38.plt                                                                             
preplot ..\UINLET\UINLET_Animate_39.plt .\UINLET_Animate_39.plt                                                                             
preplot ..\UINLET\UINLET_Animate_40.plt .\UINLET_Animate_40.plt                                                                             
preplot ..\UINLET\UINLET_Animate_41.plt .\UINLET_Animate_41.plt                                                                             
preplot ..\UINLET\UINLET_Animate_42.plt .\UINLET_Animate_42.plt                                                                             
preplot ..\UINLET\UINLET_Animate_43.plt .\UINLET_Animate_43.plt                                                                             
preplot ..\UINLET\UINLET_Animate_44.plt .\UINLET_Animate_44.plt                                                                             
preplot ..\UINLET\UINLET_Animate_45.plt .\UINLET_Animate_45.plt                                                                             
preplot ..\UINLET\UINLET_Animate_46.plt .\UINLET_Animate_46.plt                                                                             
preplot ..\UINLET\UINLET_Animate_47.plt .\UINLET_Animate_47.plt                                                                             
preplot ..\UINLET\UINLET_Animate_48.plt .\UINLET_Animate_48.plt                                                                             
preplot ..\UINLET\UINLET_Animate_49.plt .\UINLET_Animate_49.plt                                                                             
preplot ..\UINLET\UINLET_Animate_50.plt .\UINLET_Animate_50.plt                                                                             
preplot ..\UINLET\UINLET_Animate_51.plt .\UINLET_Animate_51.plt                                                                             
preplot ..\UINLET\UINLET_Animate_52.plt .\UINLET_Animate_52.plt                                                                             
preplot ..\UINLET\UINLET_Animate_53.plt .\UINLET_Animate_53.plt                                                                             
preplot ..\UINLET\UINLET_Animate_54.plt .\UINLET_Animate_54.plt                                                                             
preplot ..\UINLET\UINLET_Animate_55.plt .\UINLET_Animate_55.plt                                                                             
preplot ..\UINLET\UINLET_Animate_56.plt .\UINLET_Animate_56.plt                                                                             
preplot ..\UINLET\UINLET_Animate_57.plt .\UINLET_Animate_57.plt                                                                             
preplot ..\UINLET\UINLET_Animate_58.plt .\UINLET_Animate_58.plt                                                                             
preplot ..\UINLET\UINLET_Animate_59.plt .\UINLET_Animate_59.plt                                                                             
preplot ..\UINLET\UINLET_Animate_60.plt .\UINLET_Animate_60.plt                                                                             
preplot ..\UINLET\UINLET_Animate_61.plt .\UINLET_Animate_61.plt                                                                             
preplot ..\UINLET\UINLET_Animate_62.plt .\UINLET_Animate_62.plt                                                                             
preplot ..\UINLET\UINLET_Animate_63.plt .\UINLET_Animate_63.plt                                                                             
preplot ..\UINLET\UINLET_Animate_64.plt .\UINLET_Animate_64.plt                                                                             
preplot ..\UINLET\UINLET_Animate_65.plt .\UINLET_Animate_65.plt                                                                             
preplot ..\UINLET\UINLET_Animate_66.plt .\UINLET_Animate_66.plt                                                                             
preplot ..\UINLET\UINLET_Animate_67.plt .\UINLET_Animate_67.plt                                                                             
preplot ..\UINLET\UINLET_Animate_68.plt .\UINLET_Animate_68.plt                                                                             
preplot ..\UINLET\UINLET_Animate_69.plt .\UINLET_Animate_69.plt                                                                             
preplot ..\UINLET\UINLET_Animate_70.plt .\UINLET_Animate_70.plt                                                                             
preplot ..\UINLET\UINLET_Animate_71.plt .\UINLET_Animate_71.plt                                                                             
preplot ..\UINLET\UINLET_Animate_72.plt .\UINLET_Animate_72.plt                                                                             
preplot ..\UINLET\UINLET_Animate_73.plt .\UINLET_Animate_73.plt                                                                             
preplot ..\UINLET\UINLET_Animate_74.plt .\UINLET_Animate_74.plt                                                                             
preplot ..\UINLET\UINLET_Animate_75.plt .\UINLET_Animate_75.plt                                                                             
preplot ..\UINLET\UINLET_Animate_76.plt .\UINLET_Animate_76.plt                                                                             
preplot ..\UINLET\UINLET_Animate_77.plt .\UINLET_Animate_77.plt                                                                             
preplot ..\UINLET\UINLET_Animate_78.plt .\UINLET_Animate_78.plt                                                                             
preplot ..\UINLET\UINLET_Animate_79.plt .\UINLET_Animate_79.plt                                                                             
preplot ..\UINLET\UINLET_Animate_80.plt .\UINLET_Animate_80.plt                                                                             
preplot ..\UINLET\UINLET_Animate_81.plt .\UINLET_Animate_81.plt                                                                             
preplot ..\UINLET\UINLET_Animate_82.plt .\UINLET_Animate_82.plt                                                                             
preplot ..\UINLET\UINLET_Animate_83.plt .\UINLET_Animate_83.plt                                                                             
preplot ..\UINLET\UINLET_Animate_84.plt .\UINLET_Animate_84.plt                                                                             
preplot ..\UINLET\UINLET_Animate_85.plt .\UINLET_Animate_85.plt                                                                             
preplot ..\UINLET\UINLET_Animate_86.plt .\UINLET_Animate_86.plt                                                                             
preplot ..\UINLET\UINLET_Animate_87.plt .\UINLET_Animate_87.plt                                                                             
preplot ..\UINLET\UINLET_Animate_88.plt .\UINLET_Animate_88.plt                                                                             
preplot ..\UINLET\UINLET_Animate_89.plt .\UINLET_Animate_89.plt                                                                             
preplot ..\UINLET\UINLET_Animate_90.plt .\UINLET_Animate_90.plt                                                                             
preplot ..\UINLET\UINLET_Animate_91.plt .\UINLET_Animate_91.plt                                                                             
preplot ..\UINLET\UINLET_Animate_92.plt .\UINLET_Animate_92.plt                                                                             
preplot ..\UINLET\UINLET_Animate_93.plt .\UINLET_Animate_93.plt                                                                             
preplot ..\UINLET\UINLET_Animate_94.plt .\UINLET_Animate_94.plt                                                                             
preplot ..\UINLET\UINLET_Animate_95.plt .\UINLET_Animate_95.plt                                                                             
preplot ..\UINLET\UINLET_Animate_96.plt .\UINLET_Animate_96.plt                                                                             
preplot ..\UINLET\UINLET_Animate_97.plt .\UINLET_Animate_97.plt                                                                             
preplot ..\UINLET\UINLET_Animate_98.plt .\UINLET_Animate_98.plt                                                                             
preplot ..\UINLET\UINLET_Animate_99.plt .\UINLET_Animate_99.plt                                                                             

Write-Host "Preplotting complete!"
