	  INTEGER NI,NJ1,NJ2,NJ3,NJ,NK,NL
	  INTEGER REF_N1,REF_N2
	  INTEGER PNI,PNJ,PNL
	  INTEGER CNI,CNJ,CNL
	  INTEGER IF_WALLFUN
	  INTEGER C_NUM_ALL,C_NUM_CY,C_NUM_RECT
	  INTEGER P_NUM_CY,P_NUM_RECT,P_NUM_CY_ALL
	  INTEGER N_FOR_PLUS,N_FOR_BL
	  INTEGER NI_ADD,NJ_ADD
	  INTEGER NNN,NL_AXISY
	  REAL RATIO_TAR
	  REAL UX_CONSTANT,UY_CONSTANT,UZ_CONSTANT,PREF_CONSTANT

	  Parameter(NI=200,NJ1=150,NJ2=450,NJ3=320,NK=640,NJ=NJ1+NJ2+NJ3,NL=NK/4)
	  !PARAMETER (N_FOR_PLUS=680,N_FOR_BL=N_FOR_PLUS)
	  PARAMETER (NI_ADD=20,NJ_ADD=1)
          
      PARAMETER (NNN=NI+1+NI_ADD,NL_AXISY=NL/2+NJ+NJ_ADD)
	  Parameter(REF_N1=NI+NI_ADD,REF_N2=NL_AXISY)


	  Parameter(PNI=4,PNJ=92,PNL=2) ! assign processor number para here
	  Parameter(RATIO_TAR=0.2)
	  Parameter(UX_CONSTANT=1.649194,UY_CONSTANT=0.0,UZ_CONSTANT=0.0,PREF_CONSTANT=0.0)
	  Parameter(IF_WALLFUN=0)
	  Parameter(CNI=NI/PNI,CNJ=NJ/PNJ,CNL=NL/PNL)
	  Parameter(C_NUM_ALL=NI*NJ*NK+NI*NL*NL)
	  Parameter(C_NUM_CY=CNI*CNJ*NK,C_NUM_RECT=CNI*CNL*CNL)
	  Parameter(P_NUM_CY=(CNI+1)*(CNJ+1)*NK,P_NUM_RECT=(CNI+1)*(CNL+1)*(CNL+1) )
	  Parameter(P_NUM_CY_ALL=(NI+1)*(NJ+1)*NK)
