      INTEGER NI,NJ1,NJ2,NJ,NK,NL
      INTEGER N_FOR_PLUS,N_FOR_BL
      INTEGER NI_ADD,NJ_ADD

      PARAMETER (NI=200,NJ1=150,NJ2=450,NK=640,NJ=NJ1+NJ2)
      PARAMETER (NI_ADD=20,NJ_ADD=1)
      PARAMETER (NL=NK/4)
      PARAMETER (N_FOR_PLUS=680,N_FOR_BL=N_FOR_PLUS)
