    INTEGER  NPR , NPC
    INTEGER  NPP    
	PARAMETER( NPR  = 50 ,   NPC = 1)    
	PARAMETER( NPP = NPR * NPC ) 
	INTEGER N,nModes,nx,ny,nz,nxp
	REAL*8 L

	PARAMETER (N=80,nModes=2000)
    PARAMETER (nx=25*N,ny=2*N,nz=2*N,nxp=80)
    PARAMETER (L=0.1)
		
	INTEGER NTALL,NTP
	INTEGER N1,NMID,NXALL
	REAL*8 DT,UREF,RMAX,DELTA_RATIO

	PARAMETER(DT=2.E-4,NTALL=5000,NTP=NTALL/NPP)
	PARAMETER(UREF=1.649194,RMAX=0.10,DELTA_RATIO=0.3)
    PARAMETER(N1=160)
	PARAMETER(NXALL=N1*N1)
